ARG PROFILE
FROM davyinsa/docker-drupal:10
ARG PROFILE
RUN sed -i "s/memory_limit = 128M/memory_limit = 1024M/g" /etc/php*/php.ini
USER nginx
#VOLUME /data
RUN php -i && \
    drush site-install ${PROFILE} -y --account-pass=admin --db-url=sqlite:///tmp/.drupal.sqlite && \
    drush cr && \
    drush pm:enable -y admin_toolbar_tools admin_toolbar_search admin_toolbar_links_access_filter
USER root