name: Docker Image CI

on:
  push:
    branches: [ main ]
  schedule:
    - cron:  '30 2 * * *'
  workflow_dispatch:
    inputs:
      name:
        description: 'Reason'
        required: true
        default: 'Why??'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
  build_standard:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        drupal_version:
          - 10
          - 11.1.0-rc1
        arch:
          - 'alpine'
    steps:
    - name: alpine Build and push
      id: docker_build_alpine
      if: ${{ matrix.arch  == 'alpine' }}
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        platforms: linux/amd64,linux/arm64
        file: 'standard/Dockerfile'
        tags: 'davyinsa/docker-drupal:${{ matrix.drupal_version }}'
        build-args: |
          DRUPAL_VERSION=${{ matrix.drupal_version }}

  build_profile:
    needs: build_standard
    runs-on: ubuntu-latest
    strategy:
      matrix:
        drupal_version:
          - 10
          - 11.1.0-rc1
        arch:
          - 'alpine'
        profile:
          - 'standard'
          - 'demo_umami'
    steps:
    - name: Build and push Drupal profile ${{ matrix.profile }} installed!
      id: docker_build_alpine_profile
      if: ${{ matrix.arch  == 'alpine' }}
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        platforms: linux/amd64,linux/arm64
        file: 'standard/Dockerfile-profile'
        tags: 'davyinsa/docker-drupal:${{ matrix.drupal_version }}-${{ matrix.profile }}'
        build-args: |
          PROFILE=${{ matrix.profile }}
          DRUPAL_VERSION=${{ matrix.drupal_version }}